<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.loader._FailedTest-20240331173505" tests="2" file="unittest/loader.py" time="0.007" timestamp="2024-03-31T17:35:06" failures="0" errors="2" skipped="0">
	<testcase classname="unittest.loader._FailedTest" name="test_guest_arrival_tests" time="0.005" timestamp="2024-03-31T17:35:06">
		<error type="ImportError" message="Failed to import test module: test_guest_arrival_tests
Traceback (most recent call last):
  File &quot;C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;c:\users\izans\g88.2024.t05.ge2\src\unittest\python\test_guest_arrival_tests.py&quot;, line 4, in &lt;module&gt;
    from src.main.python.UC3MTravel.HotelManagementException import hotelManagementException
ModuleNotFoundError: No module named 'src'
"><![CDATA[Traceback (most recent call last):
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_guest_arrival_tests
Traceback (most recent call last):
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "c:\users\izans\g88.2024.t05.ge2\src\unittest\python\test_guest_arrival_tests.py", line 4, in <module>
    from src.main.python.UC3MTravel.HotelManagementException import hotelManagementException
ModuleNotFoundError: No module named 'src'

]]></error>
	</testcase>
	<testcase classname="unittest.loader._FailedTest" name="test_room_reservation_tests" time="0.002" timestamp="2024-03-31T17:35:06">
		<error type="ImportError" message="Failed to import test module: test_room_reservation_tests
Traceback (most recent call last):
  File &quot;C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;c:\users\izans\g88.2024.t05.ge2\src\unittest\python\test_room_reservation_tests.py&quot;, line 2, in &lt;module&gt;
    from src.main.python.UC3MTravel.HotelManagementException import hotelManagementException
ModuleNotFoundError: No module named 'src'
"><![CDATA[Traceback (most recent call last):
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_room_reservation_tests
Traceback (most recent call last):
  File "C:\Users\izans\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "c:\users\izans\g88.2024.t05.ge2\src\unittest\python\test_room_reservation_tests.py", line 2, in <module>
    from src.main.python.UC3MTravel.HotelManagementException import hotelManagementException
ModuleNotFoundError: No module named 'src'

]]></error>
	</testcase>
</testsuite>
